### ISSUE TITLE
three.js 0.56.0 compatibility

### ISSUE THREAD

**Issue by max-mapper** [snagy/voxel-view#3]
![Screen Shot 2013-03-11 at 3 12 39 PM](https://f.cloud.github.com/assets/39759/246230/d3566c26-8a98-11e2-9073-349b4138ee88.png)

```
DEPRECATED: Matrix4's .multiplyVector3() has been removed. Use vector.applyMatrix4( matrix ) or vector.applyProjection( matrix ) instead. three.js:3823
DEPRECATED: Matrix4's .multiplyVector3() has been removed. Use vector.applyMatrix4( matrix ) or vector.applyProjection( matrix ) instead. three.js:3823
DEPRECATED: Matrix4's .multiplyVector3() has been removed. Use vector.applyMatrix4( matrix ) or vector.applyProjection( matrix ) instead. three.js:3823
Uncaught TypeError: Object [object Object] has no method 'subSelf' 
```

i'll send a pull req later, my battery is about to die now though

**Comment by max-mapper** [comment]
oops, was using an old voxel-view, actually its just a warning:

`DEPRECATED: Matrix4's .multiplyVector3() has been removed. Use vector.applyMatrix4( matrix ) or vector.applyProjection( matrix ) instead.`

**Comment by max-mapper** [comment]
would you mind `npm push`ing a new version? then this can be closed

**Comment by snagy** [comment]
sure thing, sorry for the delay.  v 0.0.6 has these changes
